#!/bin/sh -e

if [ $# -ne 2 ]; then
    echo "old version and new version are required: e.g. release OLD_VERSION NEW_VERSION"
    exit 1
fi

OLD_VERSION=$1
NEW_VERSION=$2

rm -rf dist/*
npm run build
gsed -i "s/\"version\": \"$OLD_VERSION\"/\"version\": \"$NEW_VERSION\"/g" package.json
gsed -i "s/\"version\": \"$OLD_VERSION\"/\"version\": \"$NEW_VERSION\"/g" bower.json
git add .
git commit -m "Release $NEW_VERSION"
git tag $NEW_VERSION
git push origin master
git push origin $NEW_VERSION
npm publish
